/*
 * SPDX-License-Identifier: MIT
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2015-2026 games647, Hayston and contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.github.games647.craftapi.resolver.http;

import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Iterators;

import java.io.IOException;
import java.io.InputStream;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.Collection;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLSocketFactory;

/**
 * Implementation for rotating outgoing IPv4 addresses. It binds the next available IPv4 address to the socket
 * generated by the given oldFactory.
 */
public class RotatingSourceFactory extends SSLSocketFactory {

    //in order to be thread-safe
    private final SSLSocketFactory oldFactory;
    private Iterator<InetAddress> iterator = new Iterator<InetAddress>() {
        @Override
        public boolean hasNext() {
            return false;
        }

        @Override
        public InetAddress next() {
            throw new NoSuchElementException("Empty iterator");
        }
    };

    /**
     * Creates a new factory using the given factory for delegation.
     *
     * @param oldFactory the factory that should create sockets and establish a connection.
     */
    public RotatingSourceFactory(SSLSocketFactory oldFactory) {
        this.oldFactory = oldFactory;
    }

    /**
     * Create a new factory with the {@link HttpsURLConnection#getDefaultSSLSocketFactory()} for delegation
     */
    public RotatingSourceFactory() {
        this(HttpsURLConnection.getDefaultSSLSocketFactory());
    }

    @Override
    public Socket createSocket() throws IOException {
        Socket socket = oldFactory.createSocket();
        Optional<InetAddress> optAddress = getNextLocalAddress();
        if (optAddress.isPresent()) {
            //port 0 choose any local port that is available once the connection is established
            socket.bind(new InetSocketAddress(optAddress.get(), 0));
        }

        return socket;
    }

    @Override
    public String[] getDefaultCipherSuites() {
        return oldFactory.getDefaultCipherSuites();
    }

    @Override
    public String[] getSupportedCipherSuites() {
        return oldFactory.getSupportedCipherSuites();
    }

    @Override
    public Socket createSocket(Socket socket, String host, int port, boolean autoClose) throws IOException {
        return oldFactory.createSocket(socket, host, port, autoClose);
    }

    @Override
    public Socket createSocket(Socket socket, InputStream consumed, boolean autoClose) throws IOException {
        return oldFactory.createSocket(socket, consumed, autoClose);
    }

    @Override
    public Socket createSocket(String socket, int port) throws IOException {
        return oldFactory.createSocket(socket, port);
    }

    @Override
    public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException {
        return oldFactory.createSocket(host, port, localHost, localPort);
    }

    @Override
    public Socket createSocket(InetAddress inetAddress, int port) throws IOException {
        return oldFactory.createSocket(inetAddress, port);
    }

    @Override
    public Socket createSocket(InetAddress inetAddress, int port, InetAddress localHost, int localPort)
            throws IOException {
        return oldFactory.createSocket(inetAddress, port, localHost, localPort);
    }

    /**
     * Set the outgoing addresses. The rotating order will be the same as in the given collection.
     *
     * @param addresses all outgoing IPv4 addresses that are available or empty to disable it.
     */
    public void setOutgoingAddresses(Collection<InetAddress> addresses) {
        Set<InetAddress> copy = ImmutableSet.copyOf(addresses);
        Iterator<InetAddress> cycle = Iterators.cycle(copy);

        synchronized (this) {
            iterator = cycle;
        }
    }

    /**
     * Return the next available ip address.
     * @return the next IPv4 address from the circle or empty if there is no specified
     */
    protected Optional<InetAddress> getNextLocalAddress() {
        synchronized (this) {
            if (iterator.hasNext()) {
                return Optional.of(iterator.next());
            }

            return Optional.empty();
        }
    }
}
