# project data for Bukkit in order to register our plugin with all it's components
# Gradle expands the build version, commit hash and permission prefix.
name: FastLoginPlus
version: ${projectVersion}-${commitHash}
main: com.github.games647.fastlogin.bukkit.FastLoginBukkit

# meta data for plugin managers
authors: [Hayston, games647]
description: |
    Login plugin for premium players
website: ''
dev-url: ''

# This plugin doesn't have to be transformed for compatibility with Minecraft >= 1.13
api-version: '1.13'

softdepend:
    # We depend on either ProtocolLib or ProtocolSupport
    - ProtocolSupport
    - ProtocolLib
    # Premium variable
    - PlaceholderAPI
    # Bedrock Player Bridge
    - Geyser-Spigot
    - floodgate
    # Auth plugins
    - AuthMe
    - CrazyLogin
    - LoginSecurity
    - LogIt
    - UltraAuth
    - xAuth
    - Passky
    # Skin plugins
    - SkinsRestorer

commands:
    flp:
        description: 'FastLoginPlus commands'
        usage: '/<command> premium|cracked|delete [player]'

permissions:
    ${permissionPrefix}.command.premium:
        description: 'Label themselves as premium'
        default: true

    ${permissionPrefix}.command.premium.other:
        description: 'Label others as premium'
        children:
            ${permissionPrefix}.command.premium: true

    ${permissionPrefix}.command.cracked:
        description: 'Label themselves as cracked'
        default: op

    ${permissionPrefix}.command.cracked.other:
        description: 'Label others as cracked'
        children:
            ${permissionPrefix}.command.cracked: true

    ${permissionPrefix}.command.delete:
        description: 'Delete a player record from the FastLogin database'
        default: op
